# Generated by Django 5.1.15 on 2026-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('view', 'View Task'), ('edit', 'Edit Task'), ('assign', 'Assign Task'), ('reply', 'Reply'), ('accept', 'Accept'), ('join', 'Join Team'), ('none', 'None')], default='view', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_updated', 'Task Updated'), ('member_joined', 'Member Joined'), ('member_removed', 'Member Removed'), ('team_invite', 'Team Invite')], default='task_assigned', max_length=20),
        ),
    ]
